title: Olubowale Salisu
logo: CanadaSQL Python Excel Data Visualization Data Cleaning Statistical Analysis Critical Thinking Problem Solving Business Acumen Communication Skills Machine Learning Tableau Power BI R Programming Data Warehousin.png
theme: jekyll-theme-minimal
